### PR TITLE
Add support of Ukrainian models

### PR DESCRIPTION
**Pull request by eu9ene**

### CODE REVIEW

**Comment by abhi-agg** [comment]
@eu9ene Quick question. Have you tested this change?

**Comment by eu9ene** [comment]
> @eu9ene Quick question. Have you tested this change?

I tested locally in Nightly using `npm run once`. `uk-en` and other models in English, Spanish and Russian localized Nightly including quality estimation. Should I test in Release too? Is there a difference?

**Comment by andrenatal** [comment]
Ukrainian is being displayed as an option in the website, probably due the dynamically model registry loading? So, I will merge this with the hope it fixes it, but didn't have time to test.

Screen Shot 2022-06-23 at 3 45 12 PM

**Comment by eu9ene** [comment]
Yes, as soon as the registry is updated the language is displayed on the website. I tested it locally, it should work.

**Pull request merged**
